[build-system]
requires = ["setuptools>=61.2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest_deduplicate"
version = "0.1.6"
description = "Reports observed test coverage overlap with optional stability and mutation checks"
authors = [
    {name = "xor2003", email = "xor2003@gmx.com"},
]
dependencies = ["pytest>=7.4.4", "coverage>=7.6.1"]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "GPL"}
keywords = ["duplicate test detection","test optimization", "test efficiency"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Testing :: Unit",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Quality Assurance"
]

[project.urls]
Homepage = "https://github.com/xor2003/pytest_deduplicate"

[tool.distutils.egg_info]
tag-build = ""
tag-date = 0

[tool.setuptools]
include-package-data = false
py-modules = ["pytest_deduplicate", "pytest_deduplicate_checks"]

[project.scripts]
pytest_deduplicate = "pytest_deduplicate:main"

[project.optional-dependencies]
dev = ["build>=1", "wheel"]
